#!/bin/sh
set -e

# Update the desktop file database
if [ -x /usr/bin/update-desktop-database ]; then
    update-desktop-database -q
fi

# Update the icon caches
if [ -x /usr/bin/update-icon-caches ]; then
    update-icon-caches /usr/share/icons/hicolor /usr/share/icons/HighContrast
fi

exit 0

