function(get_ubuntu_version RESULT_VAR)
    set(${RESULT_VAR} "" PARENT_SCOPE)

    if(CMAKE_SYSTEM_NAME STREQUAL "Linux")
        if(EXISTS "/etc/lsb-release")
            file(STRINGS "/etc/lsb-release" LSB_RELEASE_ID_SHORT REGEX "^DISTRIB_ID=")
            if(LSB_RELEASE_ID_SHORT MATCHES "Ubuntu")
                file(STRINGS "/etc/lsb-release" LSB_RELEASE_VERSION REGEX "^DISTRIB_RELEASE=")
                string(REGEX REPLACE "DISTRIB_RELEASE=" "" UBUNTU_VERSION ${LSB_RELEASE_VERSION})
                set(${RESULT_VAR} ${UBUNTU_VERSION} PARENT_SCOPE)
            endif()
        endif()
    endif()
endfunction()
